CREATE TABLE [dbo].[UserAccount]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[AccountGuid] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [UN_UserAccount_AccountGUID] UNIQUE,
	[CreatedDate] DATETIME NOT NULL CONSTRAINT [DF_UserAccount_CreatedDate] DEFAULT(GETUTCDATE())
)
