CREATE TABLE [dbo].[UserAccountToken]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserAccountID] BIGINT NOT NULL,
	[TokenID] BIGINT NOT NULL, 
    [Main] BIT NOT NULL CONSTRAINT [DF_UserAccountToken_Main] DEFAULT(0)
)
